data_path: ./   # 数据存放路径

# 全局地图
global_map_filter: voxel_filter # 选择全局地图点云滤波方法，目前支持：voxel_filter, no_filter

# 局部地图
local_frame_num: 9
local_map_filter: voxel_filter # 选择滑窗小地图点云滤波方法，目前支持：voxel_filter, no_filter

# 当前帧
frame_filter: voxel_filter # 选择当前帧点云滤波方法，目前支持：voxel_filter, no_filter

# 各配置选项对应参数
## 滤波相关参数
voxel_filter:
    global_map:
            leaf_size: [0.5, 0.5, 0.5]
    local_map:
        leaf_size: [0.1, 0.1, 0.1]
    frame:
        leaf_size: [0.5, 0.5, 0.5]